version: "3.7"
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    links:
     - postgres
    depends_on: 
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=routers
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: