version: "3.7"
services: 
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=routers
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:pass123@postgres:5432/routers?schema=public
      - ELASTIC_HOST=http://elasticsearch:9200
    depends_on: 
      - elasticsearch 
      - postgres
    

volumes:
  pgdata: